noma_noma_homepage:
    pattern:  /
    defaults: { _controller: NomaNomaBundle:Default:index }

noma_noma_services:
    pattern: /services/
    defaults: { _controller: NomaNomaBundle:Services:index }

noma_noma_api_json_nodes:
    pattern: /api/json_get_nodes/
    defaults: { _controller: NomaNomaBundle:Api:jsonGetNodes }

noma_noma_api_json_nodeprops:
    pattern: /api/json_get_nodeprops/
    defaults: { _controller: NomaNomaBundle:Api:jsonGetNodeProps }

