noma_noma_homepage:
    pattern:  /
    defaults: { _controller: NomaNomaBundle:Status:index }

noma_noma_nodes:
    pattern:  /nodes/
    defaults: { _controller: NomaNomaBundle:Nodes:index }

noma_noma_services:
    pattern: /services/
    defaults: { _controller: NomaNomaBundle:Services:index }

noma_noma_nodepropdefs:
    pattern: /nodepropdefs/
    defaults: { _controller: NomaNomaBundle:NodePropDefs:index }

noma_noma_nodepropdefs_inactive:
    pattern: /nodepropdefs/inactive
    defaults: { _controller: NomaNomaBundle:NodePropDefs:getInactive }

noma_noma_nodes_inactive:
    pattern: /nodes/inactive
    defaults: { _controller: NomaNomaBundle:Nodes:getInactive }

noma_noma_api_get_nodes:
    pattern: /api/get_nodes/
    defaults: { _controller: NomaNomaBundle:Api:getNodes }

noma_noma_api_get_nodeprops:
    pattern: /api/get_nodeprops/
    defaults: { _controller: NomaNomaBundle:Api:getNodeProps }

noma_noma_api_node_add_nodeprop:
    pattern: /api/node_add_nodeprop/
    defaults: { _controller: NomaNomaBundle:Api:nodeAddNodeprop }

noma_noma_api_node_remove_nodeprop:
    pattern: /api/node_remove_nodeprop/
    defaults: { _controller: NomaNomaBundle:Api:nodeRemoveNodeprop }

