parameters:
#    noma_noma.example.class: Noma\NomaBundle\Example

services:
#    noma_noma.example:
#        class: %noma_noma.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
